<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "blog"
 *
 * Auto generated by Extension Builder 2014-05-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Blog',
	'description' => 'TYPO3 blog extension for 6.2',
	'category' => 'plugin',
	'author' => 'Frederik Vosberg',
	'author_email' => 'frederik.vosberg@rattazonk.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);